name: C/C++ CI

on:
  push:
    branches: [ "main", "actions-setup" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and run cpp tests
      run: make test
